config/routes.rb
Rails.application.routes.draw do
  resources :conteudos
  resources :horarios
  resources :status_conteudos
  resources :disciplinas
 
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]

  # GET /disciplinas
  # GET /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplina = Disciplina.new(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully created.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully updated.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: 'Disciplina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disciplina_params
      params.require(:disciplina).permit(:nome)
    end
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/views/disciplinas/_form.html.erb
<%= form_for(@disciplina) do |f| %>
  <% if @disciplina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disciplina.errors.count, "error") %> prohibited this disciplina from being saved:</h2>

      <ul>
      <% @disciplina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disciplinas/edit.html.erb
<h1>Editing Disciplina</h1>

<%= render 'form' %>

<%= link_to 'Show', @disciplina %> |
<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Disciplinas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <td><%= disciplina.nome %></td>
        <td><%= link_to 'Show', disciplina %></td>
        <td><%= link_to 'Edit', edit_disciplina_path(disciplina) %></td>
        <td><%= link_to 'Destroy', disciplina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disciplina', new_disciplina_path %>

app/views/disciplinas/new.html.erb
<h1>New Disciplina</h1>

<%= render 'form' %>

<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @disciplina.nome %>
</p>

<%= link_to 'Edit', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Back', disciplinas_path %>