config/routes.rb
Rails.application.routes.draw do
  resources :conteudos
  resources :horarios
  resources :status_conteudos
  resources :disciplinas
 
end

app/models/conteudo.rb
class Conteudo < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :status_conteudo
end

app/controllers/conteudos_controller.rb
class ConteudosController < ApplicationController
  before_action :set_conteudo, only: [:show, :edit, :update, :destroy]

  # GET /conteudos
  # GET /conteudos.json
  def index
    @conteudos = Conteudo.all
  end

  # GET /conteudos/1
  # GET /conteudos/1.json
  def show
  end

  # GET /conteudos/new
  def new
    @conteudo = Conteudo.new
    @status = StatusConteudo.all
    @disciplinas = Disciplina.order(:nome).all
  end

  # GET /conteudos/1/edit
  def edit
    @status = StatusConteudo.all
    @disciplinas = Disciplina.order(:nome).all
  end

  # POST /conteudos
  # POST /conteudos.json
  def create
    @conteudo = Conteudo.new(conteudo_params)

    respond_to do |format|
      if @conteudo.save
        format.html { redirect_to @conteudo, notice: 'Conteudo was successfully created.' }
        format.json { render :show, status: :created, location: @conteudo }
      else
        format.html { render :new }
        format.json { render json: @conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conteudos/1
  # PATCH/PUT /conteudos/1.json
  def update
    respond_to do |format|
      if @conteudo.update(conteudo_params)
        format.html { redirect_to @conteudo, notice: 'Conteudo was successfully updated.' }
        format.json { render :show, status: :ok, location: @conteudo }
      else
        format.html { render :edit }
        format.json { render json: @conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conteudos/1
  # DELETE /conteudos/1.json
  def destroy
    @conteudo.destroy
    respond_to do |format|
      format.html { redirect_to conteudos_url, notice: 'Conteudo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conteudo
      @conteudo = Conteudo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conteudo_params
      params.require(:conteudo).permit(:nome, :disciplina_id, :status_conteudo_id)
    end
end

app/helpers/conteudos_helper.rb
module ConteudosHelper
end

app/views/conteudos/_form.html.erb
<%= form_for(@conteudo) do |f| %>
  <% if @conteudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conteudo.errors.count, "error") %> prohibited this conteudo from being saved:</h2>

      <ul>
      <% @conteudo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :disciplina_id %><br>
    <%= f.collection_select :disciplina_id, @disciplinas, :id, :nome , {}, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :status_conteudo_id %><br>
    <%= f.collection_select :status_conteudo_id, @status, :id, :nome , {}, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conteudos/edit.html.erb
<h1>Editing Conteudo</h1>

<%= render 'form' %>

<%= link_to 'Show', @conteudo %> |
<%= link_to 'Back', conteudos_path %>

app/views/conteudos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Conteudos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Disciplina</th>
      <th>Status conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conteudos.each do |conteudo| %>
      <tr>
        <td><%= conteudo.nome %></td>
        <td><%= conteudo.disciplina.nome %></td>
        <td><%= conteudo.status_conteudo.nome %></td>
        <td><%= link_to 'Show', conteudo %></td>
        <td><%= link_to 'Edit', edit_conteudo_path(conteudo) %></td>
        <td><%= link_to 'Destroy', conteudo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conteudo', new_conteudo_path %>

app/views/conteudos/new.html.erb
<h1>New Conteudo</h1>

<%= render 'form' %>

<%= link_to 'Back', conteudos_path %>

app/views/conteudos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @conteudo.nome %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @conteudo.disciplina.nome %>
</p>

<p>
  <strong>Status conteudo:</strong>
  <%= @conteudo.status_conteudo.nome %>
</p>

<%= link_to 'Edit', edit_conteudo_path(@conteudo) %> |
<%= link_to 'Back', conteudos_path %>