config/routes.rb
Rails.application.routes.draw do
  resources :conteudos
  resources :horarios
  resources :status_conteudos
  resources :disciplinas
 
end

app/models/status_conteudo.rb
class StatusConteudo < ActiveRecord::Base
end

app/controllers/status_conteudos_controller.rb
class StatusConteudosController < ApplicationController
  before_action :set_status_conteudo, only: [:show, :edit, :update, :destroy]

  # GET /status_conteudos
  # GET /status_conteudos.json
  def index
    @status_conteudos = StatusConteudo.all
  end

  # GET /status_conteudos/1
  # GET /status_conteudos/1.json
  def show
  end

  # GET /status_conteudos/new
  def new
    @status_conteudo = StatusConteudo.new
  end

  # GET /status_conteudos/1/edit
  def edit
  end

  # POST /status_conteudos
  # POST /status_conteudos.json
  def create
    @status_conteudo = StatusConteudo.new(status_conteudo_params)

    respond_to do |format|
      if @status_conteudo.save
        format.html { redirect_to @status_conteudo, notice: 'Status conteudo was successfully created.' }
        format.json { render :show, status: :created, location: @status_conteudo }
      else
        format.html { render :new }
        format.json { render json: @status_conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_conteudos/1
  # PATCH/PUT /status_conteudos/1.json
  def update
    respond_to do |format|
      if @status_conteudo.update(status_conteudo_params)
        format.html { redirect_to @status_conteudo, notice: 'Status conteudo was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_conteudo }
      else
        format.html { render :edit }
        format.json { render json: @status_conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_conteudos/1
  # DELETE /status_conteudos/1.json
  def destroy
    @status_conteudo.destroy
    respond_to do |format|
      format.html { redirect_to status_conteudos_url, notice: 'Status conteudo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_conteudo
      @status_conteudo = StatusConteudo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_conteudo_params
      params.require(:status_conteudo).permit(:nome)
    end
end

app/helpers/status_conteudos_helper.rb
module StatusConteudosHelper
end

app/views/status_conteudos/_form.html.erb
<%= form_for(@status_conteudo) do |f| %>
  <% if @status_conteudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_conteudo.errors.count, "error") %> prohibited this status_conteudo from being saved:</h2>

      <ul>
      <% @status_conteudo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/status_conteudos/edit.html.erb
<h1>Editing Status Conteudo</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_conteudo %> |
<%= link_to 'Back', status_conteudos_path %>

app/views/status_conteudos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Status Conteudos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_conteudos.each do |status_conteudo| %>
      <tr>
        <td><%= status_conteudo.nome %></td>
        <td><%= link_to 'Show', status_conteudo %></td>
        <td><%= link_to 'Edit', edit_status_conteudo_path(status_conteudo) %></td>
        <td><%= link_to 'Destroy', status_conteudo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status conteudo', new_status_conteudo_path %>

app/views/status_conteudos/new.html.erb
<h1>New Status Conteudo</h1>

<%= render 'form' %>

<%= link_to 'Back', status_conteudos_path %>

app/views/status_conteudos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @status_conteudo.nome %>
</p>

<%= link_to 'Edit', edit_status_conteudo_path(@status_conteudo) %> |
<%= link_to 'Back', status_conteudos_path %>